listenAddress:
  type: "config"
  value: "0.0.0.0:7201"

logging:
  level: info

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
  # Configuration setting for generating metric IDs from tags.
  idScheme: quoted

clusters:
  - namespaces:
      - namespace: default
        retention: 48h
        type: unaggregated
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - 10.200.3.237:2379
                - 10.200.5.117:2379
                - 10.200.5.104:2379
      writeConsistencyLevel: majority
      readConsistencyLevel: unstrict_majority
